# HELP: http://docs.ros.org/en/melodic/api/robot_localization/html/configuring_robot_localization.html

ekf_node:
  ros__parameters:

    frequency: 10.0
    sensor_timeout: 0.1
    two_d_mode: true  # flat surface robot

    publish_tf: true
    publish_acceleration: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Input topics
    odom0: /wheel_encoder_odom
    odom0_config: [
      false,  false,  false,   # Position (x, y, z)
      false, false, false,     # Orientation (roll, pitch, yaw): ignore all orientation from wheel odometry
      true, false, false,      # Linear velocity (x, y, z): use x linear accel from wheel odometry
      false, false, true,      # Angular velocity (roll, pitch, yaw): using rotation around z
      false, false, false      # Linear acceleration (x, y, z): ignore acceleration from wheel odometry
    ]
    

    imu0: /imu_ros2_compatible
    imu0_frame: imu_link
    use_imu_frame: true
    imu0_config: [
      false, false, false,   # Position (x, y, z): IMUs don't measure position directly → ignore
      false, false, false,    # Orientation (roll, pitch, yaw): use yaw heading from IMU, ignore roll/pitch (upright robot)
      false, false, false,   # Linear velocity (x, y, z): IMUs don't give direct velocity → ignore
      false, false, true,    # Angular velocity (roll, pitch, yaw): use yaw rate from IMU, ignore roll/pitch rates
      false, false, false    # Linear acceleration (x, y, z): not used in EKF here (can be noisy)
    ]

    imu0_differential: false
    imu0_remove_gravitational_acceleration: false # imu_conversion_node already removes gravity

    imu0_queue_size: 10


    # odom0_config: [true, true, false,
    #                false, false, false,
    #                false, false, false,
    #                false, false, false,
    #                false, false, false]
    

    # imu0: /imu_ros2_compatible
    # imu0_frame: imu_link
    # use_imu_frame: false
    # imu0_config: [false, false, false,     # x, y, z position
    #               true,  true,  true,      # x, y, z orientation (angular velocity)
    #               false, false, false,     # x, y, z linear velocity
    #               true,  true,  true,      # x, y, z linear acceleration
    #               false, false, false]     # yaw, pitch, roll (absolute)