# DEFAULT VALUES: https://github.com/ros-navigation/navigation2_tutorials/blob/rolling/sam_bot_description/config/nav2_params.yaml
# HELP: https://docs.nav2.org/about/robots.html

# ros2 action send_goal /follow_path nav2_msgs/action/FollowPath "{path: {header: {frame_id: 'map'}, poses: [{header: {frame_id: 'map'}, pose: {position: {x: 1.5, y: 0.0, z: 0.0}, orientation: {w: 1.0}}}]}}"

####################
### BT NAVIGATOR ###
####################

# manages navigation
bt_navigator:
  ros__parameters:
    global_frame: odom # was map
    robot_base_frame: base_link
    odom_topic: /odometry/filtered

    bt_loop_duration: 5000 # VERY SLOW TOO REDUCE CPU USAGE - NOT NEEDED
    default_server_timeout: 20
    wait_for_service_timeout: 1000

    # navigator plugins
    navigators: ["navigate_to_pose", "navigate_through_poses"]

    # navigating to single pose
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"

    # navigating through a sequence of poses
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
      
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.

    # plugin_lib_names is used to add custom BT plugins to the executor (vector of strings).
    # Built-in plugins are added automatically
    # plugin_lib_names: []

    error_code_name_prefixes:
      - assisted_teleop
      - backup
      - compute_path
      - dock_robot
      - drive_on_heading
      - follow_path
      - nav_thru_poses
      - nav_to_pose
      - route
      - spin
      - undock_robot
      - wait


######################
### PLANNER SERVER ###
######################

# global path planning
planner_server:
  ros__parameters:
    expected_planner_frequency: 0.1 # VERY SLOW TOO REDUCE CPU USAGE - NOT NEEDED # 20
    costmap_update_timeout: 1.0
    introspection_mode: "disabled"
    planner_plugins: ['GridBased']
    GridBased:
      plugin: 'nav2_navfn_planner/NavfnPlanner' 
      use_astar: True
      allow_unknown: True
      tolerance: 1.0


#########################
### CONTROLLER SERVER ###
#########################

controller_server:
  ros__parameters:
    controller_frequency: 0.1 # VERY SLOW TOO REDUCE CPU USAGE - NOT NEEDED # 20
    costmap_update_timeout: 0.3
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    publish_zero_velocity: True
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    odom_topic: /odometry/filtered
    odom_duration: 0.3
    progress_checker_plugins: ["progress_checker"] # progress_checker_plugin: "progress_checker" For Humble and older
    goal_checker_plugins: ["goal_checker"] # goal_checker_plugin: "goal_checker" For Galactic and older
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 3.0 # 10

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.35 # in cm
      yaw_goal_tolerance: 3.14 # in rad (360 degrees - final yaw doesnt matter at all)
      stateful: True

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.2 # 0.26 original
      max_vel_y: 0.0
      max_vel_theta: 1.0 # 1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.0 # 0.26
      min_speed_theta: 1.0 # 1.0
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 5.0 # 3.2 original
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.0
      vx_samples: 20 # 20
      vy_samples: 0 # 5
      vtheta_samples: 10 # 20
      sim_time: 1.5 # 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      limit_vel_cmd_in_traj: True # False
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.2 # 0.02
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0


######################
### GLOBAL COSTMAP ###
######################

# long term planing
global_costmap:
  global_costmap: 
    ros__parameters:
      update_frequency: 0.0
      publish_frequency: 0.0
      global_frame: odom # was map
      robot_base_frame: base_link
      robot_radius: 0.3 # RADIUS
      #footprint: "[ [0.25, 0.20], [0.25, -0.20], [-0.25, -0.20], [-0.25, 0.20] ]" # 50 x 40 cm
      resolution: 0.05 # each cell is 5cm
      track_unknown_space: false 
      rolling_window: true # map is fixed and matches size of static map (/map topic)

      # layers that make up the costmap
      plugins: [
        "static_layer", 
        "inflation_layer"
      ]

      # uses static map from /map topic
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True  # ensures new subscribers get the latest map instantly
        map_topic: /map                      # Topic to subscribe to for static map
        first_map_only: false                # allows map to update if new map comes in
        subscribe_to_updates: true

      # expands costs outwards around obstacle to create buffer
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.5 # faster cost fall off so robot can go closer
        inflation_radius: 0.05 # 0.22
        inflate_unknown: false
        inflate_around_unknown: false

      always_send_full_costmap: True
      introspection_mode: "disabled"


#####################
### LOCAL COSTMAP ###
#####################

# short term planing / collision avoidance
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0 # in hz
      publish_frequency: 5.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true # local costmap moves with the robot
      width: 5
      height: 5
      resolution: 0.10 # 10x10cm per cell
      footprint: "[ [0.25, 0.20], [0.25, -0.20], [-0.25, -0.20], [-0.25, 0.20] ]" # 50 x 40 cm
      introspection_mode: "disabled" # disabled, metadata, contents

      # layers that make up costmap
      plugins: [
        "voxel_layer",
        "inflation_layer", 
        "range_layer"
      ] 

      # including 3d data (like from pointcloud)
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: False
        origin_z: 0.0

        # 0.03 x 11 = 33cm height of voxel layer
        z_resolution: 0.03 # height in cm per layer
        z_voxels: 11 # amount of layers

        min_obstacle_height: 0.03
        max_obstacle_height: 0.35
        mark_threshold: 1 # Minimum number of voxels in a column to mark as occupied in 2D occupancy grid

        observation_sources: pointcloud
        pointcloud:
          topic: /depth_cam_pointcloud 
          data_type: "PointCloud2"
          marking: true
          clearing: true
          min_obstacle_height: 0.03
          max_obstacle_height: 0.35
          obstacle_min_range: 0.1  
          obstacle_max_range: 2.0
          # raytrace_min_range: 0.0
          # raytrace_max_range: 3.0
          observation_persistence: 0.5  # store readings a bit

      # TOF SENSORS
      range_layer:
        plugin: "nav2_costmap_2d::RangeSensorLayer"
        enabled: true
        topics: ["/tof_front_left", "/tof_front_right", "/tof_back_left", "/tof_back_right"]  # TOF sensor_msgs/msg/Range topics
        input_sensor_type: VARIABLE  # VARIABLE to actually use the numeric data
        phi: 0.4          # 11.5 degrees
        clear_threshold: 0.2                   # Probability below which cells are marked as free.
        clear_on_max_reading: true             # Clear space if sensor reports max range
        mark_threshold: 0.8                    # Probability above which cells are marked as occupied.

      # safety margin around obstacles
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0      # faster cost fall-off
        inflation_radius: 0.35        # safe margin around obstacles
        inflate_unknown: false
        inflate_around_unknown: false
        
      always_send_full_costmap: True